# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and CobaltCore contributors
# SPDX-License-Identifier: Apache-2.0

[default.extend-words]
# Don't correct the "Ded" suffix
ded = "ded"
