{{- if .Values.rbac.helpers.enable }}
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.rbac.namespaced }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
metadata:
{{- if .Values.rbac.namespaced }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "gnmi-exporter.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ include "gnmi-exporter.resourceName" (dict "suffix" "devicemonitor-viewer-role" "context" $) }}
rules:
- apiGroups:
  - monitoring.wire.cobaltcore.dev
  resources:
  - devicemonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.wire.cobaltcore.dev
  resources:
  - devicemonitors/status
  verbs:
  - get
{{- end }}
