apiVersion: v2
name: gnmi-exporter
description: A Helm chart to distribute gnmi-exporter
type: application
version: 0.0.0+dev
keywords:
  - kubernetes
  - operator
annotations:
  kubebuilder.io/generated-by: kubebuilder
